CREATE TABLE players (
    id uuid PRIMARY KEY, name varchar(80) NOT NULL, email varchar(254) NOT NULL UNIQUE, password varchar(255) NOT NULL
);
CREATE TABLE clubs (
    id uuid PRIMARY KEY, name varchar(80) NOT NULL, description varchar(300) NOT NULL,
    owner_id uuid NOT NULL REFERENCES players, invite uuid NOT NULL UNIQUE, demo boolean NOT NULL DEFAULT false
);
CREATE TABLE members (
    id uuid PRIMARY KEY, club_id uuid NOT NULL REFERENCES clubs, player_id uuid NOT NULL REFERENCES players,
    UNIQUE (club_id, player_id)
);
CREATE TABLE games (
    id uuid PRIMARY KEY, club_id uuid NOT NULL REFERENCES clubs, title varchar(100) NOT NULL,
    location varchar(160) NOT NULL, starts_at timestamptz NOT NULL,
    team_count integer NOT NULL CHECK (team_count BETWEEN 2 AND 6),
    team_size integer NOT NULL CHECK (team_size BETWEEN 5 AND 12), cancelled boolean NOT NULL DEFAULT false
);
CREATE INDEX games_club_start_idx ON games (club_id, starts_at);
CREATE TABLE teams (
    id uuid PRIMARY KEY, game_id uuid NOT NULL REFERENCES games, ordinal integer NOT NULL,
    name varchar(60) NOT NULL, color varchar(7) NOT NULL, captain_id uuid REFERENCES players,
    formation varchar(10) NOT NULL CHECK (formation IN ('2-2','1-2-1','3-1')), version bigint NOT NULL DEFAULT 0,
    UNIQUE (game_id, ordinal), UNIQUE (game_id, captain_id), UNIQUE (id, game_id)
);
CREATE TABLE participations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, game_id uuid NOT NULL REFERENCES games,
    player_id uuid NOT NULL REFERENCES players, status varchar(12) NOT NULL CHECK (status IN ('CONFIRMED','WAITING')),
    team_id uuid, slot integer CHECK (slot BETWEEN 0 AND 4),
    UNIQUE (game_id, player_id), UNIQUE (team_id, slot),
    FOREIGN KEY (team_id, game_id) REFERENCES teams (id, game_id),
    CHECK (slot IS NULL OR team_id IS NOT NULL), CHECK (status='CONFIRMED' OR team_id IS NULL)
);
CREATE INDEX participations_game_queue_idx ON participations (game_id, status, id);

CREATE TABLE SPRING_SESSION (
    PRIMARY_ID CHAR(36) NOT NULL PRIMARY KEY, SESSION_ID CHAR(36) NOT NULL, CREATION_TIME BIGINT NOT NULL,
    LAST_ACCESS_TIME BIGINT NOT NULL, MAX_INACTIVE_INTERVAL INT NOT NULL, EXPIRY_TIME BIGINT NOT NULL,
    PRINCIPAL_NAME VARCHAR(100)
);
CREATE UNIQUE INDEX SPRING_SESSION_IX1 ON SPRING_SESSION (SESSION_ID);
CREATE INDEX SPRING_SESSION_IX2 ON SPRING_SESSION (EXPIRY_TIME);
CREATE INDEX SPRING_SESSION_IX3 ON SPRING_SESSION (PRINCIPAL_NAME);
CREATE TABLE SPRING_SESSION_ATTRIBUTES (
    SESSION_PRIMARY_ID CHAR(36) NOT NULL REFERENCES SPRING_SESSION(PRIMARY_ID) ON DELETE CASCADE,
    ATTRIBUTE_NAME VARCHAR(200) NOT NULL, ATTRIBUTE_BYTES BYTEA NOT NULL,
    PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME)
);
