ALTER TABLE clubs
    ADD COLUMN barbecue_frequency varchar(20) NOT NULL DEFAULT 'NONE'
    CHECK (barbecue_frequency IN ('NONE', 'MONTHLY', 'EVERY_2_MONTHS', 'EVERY_3_MONTHS'));

CREATE TABLE barbecue_series (
    id uuid PRIMARY KEY,
    club_id uuid NOT NULL UNIQUE REFERENCES clubs,
    frequency varchar(20) NOT NULL CHECK (frequency IN ('MONTHLY', 'EVERY_2_MONTHS', 'EVERY_3_MONTHS')),
    anchor_starts_at timestamptz NOT NULL,
    time_zone varchar(80) NOT NULL,
    location varchar(160) NOT NULL,
    active boolean NOT NULL DEFAULT true,
    next_occurrence_index integer NOT NULL DEFAULT 0 CHECK (next_occurrence_index >= 0),
    UNIQUE (id, club_id)
);

CREATE TABLE barbecues (
    id uuid PRIMARY KEY,
    club_id uuid NOT NULL REFERENCES clubs,
    series_id uuid,
    occurrence_index integer NOT NULL DEFAULT 0 CHECK (occurrence_index >= 0),
    starts_at timestamptz NOT NULL,
    location varchar(160) NOT NULL,
    cancelled boolean NOT NULL DEFAULT false,
    invite_token uuid NOT NULL UNIQUE,
    FOREIGN KEY (series_id, club_id) REFERENCES barbecue_series (id, club_id),
    UNIQUE (series_id, occurrence_index)
);
CREATE INDEX barbecues_club_start_idx ON barbecues (club_id, starts_at);

CREATE TABLE barbecue_attendance (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    barbecue_id uuid NOT NULL REFERENCES barbecues,
    player_id uuid NOT NULL REFERENCES players,
    created_at timestamptz NOT NULL,
    UNIQUE (barbecue_id, player_id)
);
CREATE INDEX barbecue_attendance_event_idx ON barbecue_attendance (barbecue_id, created_at);
